version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - dev-db
    restart: always
    volumes: 
    - /nfs/homes/hfanzaou/data/app:/usr/src/app/backend/uploads/
    networks:
      - mynet

  dev-db:
    container_name: database
    image: postgres:bullseye
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - mynet
    volumes:
      - db:/var/lib/postgresql/data/

networks:
  mynet:  

volumes:
  db:
