version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
       - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2306
      POSTGRES_DB: nest
    networks:
      - mynet
networks:
  mynet:  
