version: '3.8'
services:
  dev-db:
    image: postgres:bullseye
    ports:
       - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2306cp 
      POSTGRES_DB: nest
    networks:
      - mynet
networks:
  mynet:  
